name: Tutorial

api: [3.0.0, 4.0.0]

version: 0.0.1

main: Crow\xD\Main

author:

 - ceepkev77

 - Crow balde

load: STARTUP

commands:

  Heal:

    description: ยง4Heal Plugin by Crow Balde

    usage: "/Heal"

    permission: Heal.rechte

  YT:

    description: ยง4YT

    usage: "/YT"

    permissions: YT.rechte
